name: CI

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "nonebot_plugin_exe_code/**"
      - "tests/**"
      - ".github/workflows/ci.yml"
      - "pyproject.toml"
      - "uv.lock"

jobs:
  ruff:
    name: Ruff Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Ruff Lint
        uses: astral-sh/ruff-action@v2
        with:
          src: >-
            nonebot_plugin_exe_code/
            tests/

  basedpyright:
    name: BasedPyright Lint
    runs-on: ubuntu-latest
    needs: ruff
    concurrency:
      group: basedpyright-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-extras --all-groups

      - name: Configure venv
        run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Run BasedPyright
        run: uv tool run basedpyright nonebot_plugin_exe_code/ tests/ --pythonpath ./.venv/bin/python

  test:
    name: Test & Coverage
    runs-on: ubuntu-latest
    needs: basedpyright
    concurrency:
      group: test-coverage-${{ github.ref }}-${{ matrix.python-version }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-extras --all-groups

      - name: Run Pytest
        run: uv run pytest --cov=nonebot_plugin_exe_code --cov-report=xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
