name: CI

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "nonebot_plugin_exe_code/**"
      - "tests/**"
      - ".github/workflows/ci.yml"
      - "pyproject.toml"
      - "uv.lock"

jobs:
  lint:
    name: Pyright Lint
    runs-on: ubuntu-latest
    concurrency:
      group: pyright-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --python 3.12

      - name: Configure venv
        run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Run Pyright
        uses: jakebailey/pyright-action@v2

  test:
    name: Test & Coverage
    runs-on: ubuntu-latest
    needs: lint
    concurrency:
      group: test-coverage-${{ github.ref }}-${{ matrix.python-version }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --python ${{ matrix.python-version }}

      - name: Run Pytest
        run: |
            uv run coverage run --source nonebot_plugin_exe_code -m pytest tests
            uv run coverage xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
