name: Code Coverage

on:
  push:
    paths:
      - "nonebot_plugin_exe_code/**"
      - "tests/**"
      - ".github/workflows/codecov.yml"
      - "pyproject.toml"
      - "pdm.lock"
  pull_request:
    paths:
      - "nonebot_plugin_exe_code/**"
      - "tests/**"
      - ".github/workflows/codecov.yml"
      - "pyproject.toml"
      - "pdm.lock"

jobs:
  test:
    name: Test Coverage
    runs-on: ubuntu-latest
    concurrency:
      group: test-coverage-${{ github.ref }}-${{ matrix.python-version }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          uv python install ${{ matrix.python-version }}
          uv sync --python ${{ matrix.python-version }}

      - name: Run Pytest
        run: |
            uv run coverage run --source nonebot_plugin_exe_code -m pytest tests
            uv run coverage xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
