name: Code Coverage

on:
  push:
    paths:
      - "nonebot_plugin_exe_code/**"
      - "tests/**"
      - ".github/workflows/codecov.yml"
      - "pyproject.toml"
      - "pdm.lock"
  pull_request:
    paths:
      - "nonebot_plugin_exe_code/**"
      - "tests/**"
      - ".github/workflows/codecov.yml"
      - "pyproject.toml"
      - "pdm.lock"

jobs:
  test:
    name: Test Coverage
    runs-on: ubuntu-latest
    concurrency:
      group: test-coverage-${{ github.ref }}-${{ matrix.python-version }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true

      - name: Install dependencies
        run: pdm install

      - name: Run Pytest
        run: |
            pdm test
            pdm report

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
